/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareShareIdRouteImport } from './routes/share/$shareId'
import { Route as OpenrouterCallbackRouteImport } from './routes/openrouter/callback'
import { Route as CChatIdRouteImport } from './routes/c/$chatId'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as ApiTypingRouteImport } from './routes/api/typing'
import { Route as ApiOpenrouterKeyRouteImport } from './routes/api/openrouter-key'
import { Route as ApiMonitoringRouteImport } from './routes/api/monitoring'
import { Route as ApiModelsRouteImport } from './routes/api/models'
import { Route as ApiWorkflowGenerateTitleRouteImport } from './routes/api/workflow/generate-title'
import { Route as ApiWorkflowExportChatRouteImport } from './routes/api/workflow/export-chat'
import { Route as ApiWorkflowDeleteAccountRouteImport } from './routes/api/workflow/delete-account'
import { Route as ApiWorkflowCleanupRouteImport } from './routes/api/workflow/cleanup'
import { Route as ApiOgShareShareIdRouteImport } from './routes/api/og/share/$shareId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareShareIdRoute = ShareShareIdRouteImport.update({
  id: '/share/$shareId',
  path: '/share/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenrouterCallbackRoute = OpenrouterCallbackRouteImport.update({
  id: '/openrouter/callback',
  path: '/openrouter/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const CChatIdRoute = CChatIdRouteImport.update({
  id: '/c/$chatId',
  path: '/c/$chatId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTypingRoute = ApiTypingRouteImport.update({
  id: '/api/typing',
  path: '/api/typing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenrouterKeyRoute = ApiOpenrouterKeyRouteImport.update({
  id: '/api/openrouter-key',
  path: '/api/openrouter-key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMonitoringRoute = ApiMonitoringRouteImport.update({
  id: '/api/monitoring',
  path: '/api/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelsRoute = ApiModelsRouteImport.update({
  id: '/api/models',
  path: '/api/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkflowGenerateTitleRoute =
  ApiWorkflowGenerateTitleRouteImport.update({
    id: '/api/workflow/generate-title',
    path: '/api/workflow/generate-title',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWorkflowExportChatRoute = ApiWorkflowExportChatRouteImport.update({
  id: '/api/workflow/export-chat',
  path: '/api/workflow/export-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkflowDeleteAccountRoute =
  ApiWorkflowDeleteAccountRouteImport.update({
    id: '/api/workflow/delete-account',
    path: '/api/workflow/delete-account',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWorkflowCleanupRoute = ApiWorkflowCleanupRouteImport.update({
  id: '/api/workflow/cleanup',
  path: '/api/workflow/cleanup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgShareShareIdRoute = ApiOgShareShareIdRouteImport.update({
  id: '/api/og/share/$shareId',
  path: '/api/og/share/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/api/models': typeof ApiModelsRoute
  '/api/monitoring': typeof ApiMonitoringRoute
  '/api/openrouter-key': typeof ApiOpenrouterKeyRoute
  '/api/typing': typeof ApiTypingRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/c/$chatId': typeof CChatIdRoute
  '/openrouter/callback': typeof OpenrouterCallbackRoute
  '/share/$shareId': typeof ShareShareIdRoute
  '/api/workflow/cleanup': typeof ApiWorkflowCleanupRoute
  '/api/workflow/delete-account': typeof ApiWorkflowDeleteAccountRoute
  '/api/workflow/export-chat': typeof ApiWorkflowExportChatRoute
  '/api/workflow/generate-title': typeof ApiWorkflowGenerateTitleRoute
  '/api/og/share/$shareId': typeof ApiOgShareShareIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/api/models': typeof ApiModelsRoute
  '/api/monitoring': typeof ApiMonitoringRoute
  '/api/openrouter-key': typeof ApiOpenrouterKeyRoute
  '/api/typing': typeof ApiTypingRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/c/$chatId': typeof CChatIdRoute
  '/openrouter/callback': typeof OpenrouterCallbackRoute
  '/share/$shareId': typeof ShareShareIdRoute
  '/api/workflow/cleanup': typeof ApiWorkflowCleanupRoute
  '/api/workflow/delete-account': typeof ApiWorkflowDeleteAccountRoute
  '/api/workflow/export-chat': typeof ApiWorkflowExportChatRoute
  '/api/workflow/generate-title': typeof ApiWorkflowGenerateTitleRoute
  '/api/og/share/$shareId': typeof ApiOgShareShareIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/api/models': typeof ApiModelsRoute
  '/api/monitoring': typeof ApiMonitoringRoute
  '/api/openrouter-key': typeof ApiOpenrouterKeyRoute
  '/api/typing': typeof ApiTypingRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/c/$chatId': typeof CChatIdRoute
  '/openrouter/callback': typeof OpenrouterCallbackRoute
  '/share/$shareId': typeof ShareShareIdRoute
  '/api/workflow/cleanup': typeof ApiWorkflowCleanupRoute
  '/api/workflow/delete-account': typeof ApiWorkflowDeleteAccountRoute
  '/api/workflow/export-chat': typeof ApiWorkflowExportChatRoute
  '/api/workflow/generate-title': typeof ApiWorkflowGenerateTitleRoute
  '/api/og/share/$shareId': typeof ApiOgShareShareIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/privacy'
    | '/settings'
    | '/terms'
    | '/api/models'
    | '/api/monitoring'
    | '/api/openrouter-key'
    | '/api/typing'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/c/$chatId'
    | '/openrouter/callback'
    | '/share/$shareId'
    | '/api/workflow/cleanup'
    | '/api/workflow/delete-account'
    | '/api/workflow/export-chat'
    | '/api/workflow/generate-title'
    | '/api/og/share/$shareId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/privacy'
    | '/settings'
    | '/terms'
    | '/api/models'
    | '/api/monitoring'
    | '/api/openrouter-key'
    | '/api/typing'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/c/$chatId'
    | '/openrouter/callback'
    | '/share/$shareId'
    | '/api/workflow/cleanup'
    | '/api/workflow/delete-account'
    | '/api/workflow/export-chat'
    | '/api/workflow/generate-title'
    | '/api/og/share/$shareId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/privacy'
    | '/settings'
    | '/terms'
    | '/api/models'
    | '/api/monitoring'
    | '/api/openrouter-key'
    | '/api/typing'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/c/$chatId'
    | '/openrouter/callback'
    | '/share/$shareId'
    | '/api/workflow/cleanup'
    | '/api/workflow/delete-account'
    | '/api/workflow/export-chat'
    | '/api/workflow/generate-title'
    | '/api/og/share/$shareId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PrivacyRoute: typeof PrivacyRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  ApiModelsRoute: typeof ApiModelsRoute
  ApiMonitoringRoute: typeof ApiMonitoringRoute
  ApiOpenrouterKeyRoute: typeof ApiOpenrouterKeyRoute
  ApiTypingRoute: typeof ApiTypingRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  CChatIdRoute: typeof CChatIdRoute
  OpenrouterCallbackRoute: typeof OpenrouterCallbackRoute
  ShareShareIdRoute: typeof ShareShareIdRoute
  ApiWorkflowCleanupRoute: typeof ApiWorkflowCleanupRoute
  ApiWorkflowDeleteAccountRoute: typeof ApiWorkflowDeleteAccountRoute
  ApiWorkflowExportChatRoute: typeof ApiWorkflowExportChatRoute
  ApiWorkflowGenerateTitleRoute: typeof ApiWorkflowGenerateTitleRoute
  ApiOgShareShareIdRoute: typeof ApiOgShareShareIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$shareId': {
      id: '/share/$shareId'
      path: '/share/$shareId'
      fullPath: '/share/$shareId'
      preLoaderRoute: typeof ShareShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openrouter/callback': {
      id: '/openrouter/callback'
      path: '/openrouter/callback'
      fullPath: '/openrouter/callback'
      preLoaderRoute: typeof OpenrouterCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$chatId': {
      id: '/c/$chatId'
      path: '/c/$chatId'
      fullPath: '/c/$chatId'
      preLoaderRoute: typeof CChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/typing': {
      id: '/api/typing'
      path: '/api/typing'
      fullPath: '/api/typing'
      preLoaderRoute: typeof ApiTypingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openrouter-key': {
      id: '/api/openrouter-key'
      path: '/api/openrouter-key'
      fullPath: '/api/openrouter-key'
      preLoaderRoute: typeof ApiOpenrouterKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/monitoring': {
      id: '/api/monitoring'
      path: '/api/monitoring'
      fullPath: '/api/monitoring'
      preLoaderRoute: typeof ApiMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/models': {
      id: '/api/models'
      path: '/api/models'
      fullPath: '/api/models'
      preLoaderRoute: typeof ApiModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflow/generate-title': {
      id: '/api/workflow/generate-title'
      path: '/api/workflow/generate-title'
      fullPath: '/api/workflow/generate-title'
      preLoaderRoute: typeof ApiWorkflowGenerateTitleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflow/export-chat': {
      id: '/api/workflow/export-chat'
      path: '/api/workflow/export-chat'
      fullPath: '/api/workflow/export-chat'
      preLoaderRoute: typeof ApiWorkflowExportChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflow/delete-account': {
      id: '/api/workflow/delete-account'
      path: '/api/workflow/delete-account'
      fullPath: '/api/workflow/delete-account'
      preLoaderRoute: typeof ApiWorkflowDeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflow/cleanup': {
      id: '/api/workflow/cleanup'
      path: '/api/workflow/cleanup'
      fullPath: '/api/workflow/cleanup'
      preLoaderRoute: typeof ApiWorkflowCleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/share/$shareId': {
      id: '/api/og/share/$shareId'
      path: '/api/og/share/$shareId'
      fullPath: '/api/og/share/$shareId'
      preLoaderRoute: typeof ApiOgShareShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PrivacyRoute: PrivacyRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  ApiModelsRoute: ApiModelsRoute,
  ApiMonitoringRoute: ApiMonitoringRoute,
  ApiOpenrouterKeyRoute: ApiOpenrouterKeyRoute,
  ApiTypingRoute: ApiTypingRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  CChatIdRoute: CChatIdRoute,
  OpenrouterCallbackRoute: OpenrouterCallbackRoute,
  ShareShareIdRoute: ShareShareIdRoute,
  ApiWorkflowCleanupRoute: ApiWorkflowCleanupRoute,
  ApiWorkflowDeleteAccountRoute: ApiWorkflowDeleteAccountRoute,
  ApiWorkflowExportChatRoute: ApiWorkflowExportChatRoute,
  ApiWorkflowGenerateTitleRoute: ApiWorkflowGenerateTitleRoute,
  ApiOgShareShareIdRoute: ApiOgShareShareIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
